apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: eng-atestados-go-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eng-atestados-go
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

