apiVersion: v1
kind: Service
metadata:
  name: eng-atestados-go-service
spec:
  selector:
    app: eng-atestados-go
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
